services:
  # Backend API service
  - type: web
    name: crypto-converter-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TOKEN_METRICS_API_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false

  # Frontend static site
  - type: web
    name: crypto-converter-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://crypto-converter-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 